//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.05 at 04:46:17 PM ALMT 
//


package kz.gatewaysoap.requester;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="requester" type="{http://www.gatewaySOAP.kz/requester}requesterOK"/&gt;
 *         &lt;element name="sender" type="{http://www.gatewaySOAP.kz/requester}requesterERROR"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "requester",
        "sender"
})
@XmlRootElement(name = "getResponseInfoResponse")
public class GetResponseInfoResponse {

    @XmlElement(required = true)
    protected RequesterOK requester;
    @XmlElement(required = true)
    protected RequesterERROR sender;

    /**
     * Gets the value of the requester property.
     *
     * @return possible object is
     * {@link RequesterOK }
     */
    public RequesterOK getRequester() {
        return requester;
    }

    /**
     * Sets the value of the requester property.
     *
     * @param value allowed object is
     *              {@link RequesterOK }
     */
    public void setRequester(RequesterOK value) {
        this.requester = value;
    }

    /**
     * Gets the value of the sender property.
     *
     * @return possible object is
     * {@link RequesterERROR }
     */
    public RequesterERROR getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     *
     * @param value allowed object is
     *              {@link RequesterERROR }
     */
    public void setSender(RequesterERROR value) {
        this.sender = value;
    }

}
